version: '3'

services:
  smart-approval-bot:
    build: .
    container_name: smart-approval-bot
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    environment:
      - SERVER_PORT=8080
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_NAME=${GITHUB_APP_NAME}
      - GITHUB_APP_PRIVATE_KEY_PATH=/app/config/private-key.pem
      - GITHUB_APP_WEBHOOK_SECRET=${GITHUB_APP_WEBHOOK_SECRET}
      - LOGGING_LEVEL_COM_GITHUB_SMARTAPPROVALBOT=INFO
    restart: unless-stopped
